# -*- coding: utf-8 -*-
"""Meeting minutes generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6dj8CY99fkAbXk2Mas8xfGvduWTf0X3
"""

#-------------------------
#meeting minutes generator
#-------------------------
import pandas  as pd
from datetime import datetime

print("meeting miutes generator\n")

# user inputs
meeting_title=input("enter meeting title:")
date=input("enter meeting date(DD-MM-YYYY):")
time=input("enter meeting time:")
participants=input("enter participants (comma seperated):")
agenda=input("enter agenda points (comma seperated):")
decisions=input("enter decision taken (comma seperated):")
action_items=input("enter action items (comma seperated):")
prepared_by=input("prepared by:")

#process inputs
participants_lists=[p.strip() for p in participants.split(",")if p.strip()]
agenda_lists=[a.strip() for a in agenda.split(",")if a.strip()]
decisions_lists=[d.strip() for d in decisions.split(",")if d.strip()]
actions_lists=[t.strip() for t in action_items.split(",")if t.strip()]

#create structure meeting minutes
minutes = {
    "Meeting Title":meeting_title,
    "Date":date,
    "Time":time,
    "participants":",".join(participants_lists),
    "Agenda":";".join(agenda_lists),
    "Decision Taken":";".join(decisions_lists),
    "Action Items":";".join(actions_lists),
    "Prepared By":prepared_by,
    "Generated On":datetime.now().strftime("%d-%m-%Y %H:%M:%S")
}

#convert to Data frame
df = pd.DataFrame(list(minutes.items()),columns=["Field","Detailed"])

print("\n Meeting minutes generated successfully")
display(df)

#save as CSV
df.to_csv("meeting minutes.csv",index=False)
print("\nFile saved as meeting_minutes.csv")