# -*- coding: utf-8 -*-
"""Text-Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PoFuMrSueJ0yWQT764tmyBzGEEkLI1FI
"""

pip install transformers torch -q

#import pipelines
from transformers import pipeline

#create text generation model
generator = pipeline("text-generation")

#give strating text
result = generator("artificial intelligence wil",max_length=30)

#print result
print(result[0]["generated_text"])