# -*- coding: utf-8 -*-
"""Timetable Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EfryAz2b0dgs2ZV8VI4b_06TFrjbzZXR
"""

import pandas as pd
import random

print("TIMETABLE GENERATOR\n")

#user inputs
subject_input=input("enter subjects(comma separated):")
days_input=input("enter days(comma separated):")
periods_per_day=int(input("enter number of periods per day"))

#process inputs
subjects=[s.strip() for s in subject_input.split(",")if s.strip()]
days=[d.strip() for d in days_input.split(",")if d.strip()]

#validation
if len(subjects)==0 or len(days)==0 or periods_per_day<=0:
    print("invalid input. Please try again ")
else:
    timetable ={}

    for day in days:
        timetable[day]=random.choices(subjects,k=periods_per_day)

    #create dataframe
    df=pd.DataFrame(timetable)
    df.idex =[f"period {i+1}" for i in range(periods_per_day)]

    print("\n timetable generated sucessfully")
    display(df)

    #save timetable
    df.to_csv("timetable.csv")
    print("\ntimeyable saved as timetable.csv")

